import { AlertCircle, ArrowUpRight } from "lucide-react";

export default function Safety() {
  return (
    <section id="seguranca" className="relative overflow-hidden py-24 lg:py-32">
      <div aria-hidden="true" className="absolute inset-x-0 top-20 mx-auto h-[460px] max-w-5xl rounded-[50px] bg-gradient-brand opacity-10 blur-3xl" />
      <div className="site-container relative overflow-hidden rounded-[34px] bg-navy px-7 py-10 text-white shadow-2xl shadow-navy/15 sm:px-12 sm:py-14 lg:px-20 lg:py-20">
        <div aria-hidden="true" className="absolute -right-16 -top-28 h-72 w-72 rounded-full border-[45px] border-white/5" /><div aria-hidden="true" className="absolute -bottom-40 left-1/3 h-72 w-72 rounded-full bg-pink/20 blur-3xl" />
        <div className="relative grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:gap-20"><div><span className="eyebrow text-white/80 before:bg-peach">clareza e cuidado</span><h2 className="mt-5 text-4xl font-black tracking-[-0.04em] sm:text-5xl">Tecnologia para apoiar. Pessoas para cuidar.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">A EscutIA oferece um espaço de conversa e reflexão. Ela não substitui psicólogos, psiquiatras ou outros profissionais de saúde e não realiza diagnósticos.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full border border-white/15 bg-white/8 px-4 py-2 text-sm font-semibold text-white/75">Sem diagnósticos</span><span className="rounded-full border border-white/15 bg-white/8 px-4 py-2 text-sm font-semibold text-white/75">Sem julgamentos</span></div><a href="/privacidade" className="group mt-7 inline-flex items-center gap-2 text-sm font-bold text-peach transition-[color] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-peach focus-visible:ring-offset-2 focus-visible:ring-offset-navy">Leia como tratamos seus dados <ArrowUpRight aria-hidden="true" size={15} className="transition-transform duration-200 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 motion-reduce:transition-none" /></a></div><div className="rounded-[26px] border border-white/10 bg-white/10 p-6 backdrop-blur sm:p-7"><div aria-hidden="true" className="grid h-12 w-12 place-items-center rounded-2xl bg-peach text-navy"><AlertCircle size={22} strokeWidth={2.25} /></div><h3 className="mt-6 text-xl font-extrabold">Em situações de crise</h3><p className="mt-3 leading-7 text-white/65">Se você estiver em risco ou precisar de ajuda imediata, procure os serviços de emergência da sua região ou converse com um profissional de saúde de confiança.</p><a href="/termos" className="group mt-6 inline-flex items-center gap-2 text-sm font-bold text-peach transition-[color] hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-peach focus-visible:ring-offset-2 focus-visible:ring-offset-navy">Conheça os limites da plataforma <ArrowUpRight aria-hidden="true" size={15} className="transition-transform duration-200 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 motion-reduce:transition-none" /></a></div></div>
      </div>
    </section>
  );
}
